language:
  - python
jobs:
  include:
    - name: "Python 3.7.0 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      script:
        - set -e  # If any of the following steps fail, just stop at that point.
        - make -C docs html  # Build the documentation.
        - pip3 install doctr
        - doctr deploy --built-docs docs/build/html .  # Publish the documentation.

install:
  # Install this package and the packages listed in requirements.txt.
  - pip3 install --upgrade pip
  - pip3 install . #pip install --upgrade pip
  # Install extra requirements for running tests and building docs.
  - pip3 install -r requirements-dev.txt

notifications:
  email: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

env:
  global:
  # Doctr deploy key for vstadnytskyi/icarus-nmr
  - secure: "HfuJfMqjNVD4GJh9E6KpMMZSeQBD6Irr8I4bZLotJcWOsCBsxLP+myWgFF6Dt+CUtiH7oG8pkSE9pE0Ma7H0eM06ljVVXHKPU66puWHdmCeHgoCfOnbLCNV6H+00GDQXcwbvF69/krD09Wko8cLFjWalL9dx6h73MG5kiNIz3e/zPSiF/eisH7gCCux2M40qSXYEDJqTv3WNuaoUtbSoyCFEcj0xEwhAy7caYVGlCFuTaEiIhBD/1hq3msbSukWggOlxQD/7g+3b3IFNWwjP1xNsXpEOm7LbWIpxuLDYmWzwkFxRGTrjzlknIHTkBsVcMza4tb7hY5IRJ5mMYarQSkct/83rWzmn8Z4ZcXxudzUyTVJ8tjncq8cSArIaL5wrN85QaKkrgU8I32GUw5JNMYNQWLtOzgi5Gw4OQV56o8qwDMDbRXPwTEsoiiaVFP1RMbTrPgUMHkPhf8Ee34UX6Uzv/lY+EijVUcCFrCvZs3YGr5dZKQEWmlyrIrYKRGuVzSaNNGmG9jlrJHh/JDyjCZo6ZmH1vMoeNcEk66ttOHxL7oyoGIUCRLnOgSv+Gee9e4t+Iu3ZVvopBGBMjG7IOuRtbM5FKRvBkwHtjWG5bAGWts7wU87btidJc5krNmsDLRu8RJ3xNYA4eFWO+PDSUjm3iTBwtPj62X7PguJsbow="
